import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:lazervault/core/notifications/notification_route_resolver.dart';
import 'package:lazervault/core/notifications/notification_target.dart';
import 'package:lazervault/core/types/app_routes.dart';

/// Checks the client against links the SERVER actually produced.
///
/// `test/fixtures/notification_deeplinks.json` is generated by the real Go
/// builder (`UPDATE_DEEPLINK_FIXTURE=1 go test ./internal/service/ -run
/// TestEmitDeepLinkFixture` in notifications-service). Without this, the Go
/// tests and the Dart tests each pin the URL shape against their own
/// hand-written expectations — so both can stay green while drifting apart,
/// which is exactly how a seam between a Go service and a Flutter app breaks.
///
/// Here the app parses what the server emits. If either side changes the URL
/// shape or a payload key, this fails.
void main() {
  late List<dynamic> fixture;

  setUpAll(() {
    final f = File('test/fixtures/notification_deeplinks.json');
    expect(
      f.existsSync(),
      isTrue,
      reason: 'fixture missing — regenerate it from notifications-service',
    );
    fixture = jsonDecode(f.readAsStringSync()) as List<dynamic>;
    expect(fixture, isNotEmpty);
  });

  test('every server-minted app link parses back to its type and data', () {
    for (final raw in fixture) {
      final c = raw as Map<String, dynamic>;
      final type = c['type'] as String;
      final parsed = NotificationLink.parse(Uri.parse(c['app_link'] as String));

      expect(parsed, isNotNull, reason: 'app_link for $type did not parse');
      expect(parsed!.type, type);
    }
  });

  test('the universal-link form parses identically to the app-scheme form', () {
    // Email and SMS carry the https form; a push carries the custom scheme.
    // They must land on the same place or a link behaves differently depending
    // on which channel delivered it.
    for (final raw in fixture) {
      final c = raw as Map<String, dynamic>;
      final app = NotificationLink.parse(Uri.parse(c['app_link'] as String));
      final web = NotificationLink.parse(Uri.parse(c['web_link'] as String));

      expect(web, isNotNull, reason: 'web_link for ${c['type']} did not parse');
      expect(web!.type, app!.type);
      expect(web.data, app.data);
    }
  });

  test('every server-minted link resolves to a destination', () {
    for (final raw in fixture) {
      final c = raw as Map<String, dynamic>;
      final type = c['type'] as String;
      final target = NotificationRouteResolver.resolveUri(
          Uri.parse(c['app_link'] as String));
      expect(
        target,
        isNotNull,
        reason: '$type resolved nowhere — it would land on the feed',
      );
    }
  });

  test('resolving from the link matches resolving from the raw payload', () {
    // A push tap resolves from `data`; a tapped email link resolves from the
    // URL. The URL carries only the routing keys, so this is what proves the
    // routing keys are sufficient — that nothing needed for the destination was
    // left behind as a display-only field.
    for (final raw in fixture) {
      final c = raw as Map<String, dynamic>;
      final type = c['type'] as String;
      final data = Map<String, dynamic>.from(c['data'] as Map);

      final fromPayload = NotificationRouteResolver.resolve(type, data);
      final fromLink = NotificationRouteResolver.resolveUri(
          Uri.parse(c['app_link'] as String));

      expect(fromLink?.route, fromPayload?.route,
          reason: '$type routes differently via link vs payload');
      expect(
          fromLink?.arguments?.toString(), fromPayload?.arguments?.toString(),
          reason: '$type passes different arguments via link vs payload');
    }
  });

  test('links carry no display fields', () {
    // A deep link says WHICH record. Amount, currency and counterparty names in
    // a URL would leak transaction detail into email bodies, SMS bodies, and
    // anything that logs a URL or sends a referrer.
    const leaky = [
      'amount',
      'currency',
      'sender_name',
      'receiver_name',
      'code'
    ];
    for (final raw in fixture) {
      final c = raw as Map<String, dynamic>;
      for (final key in leaky) {
        expect(c['app_link'], isNot(contains('$key=')),
            reason: '${c['type']} leaked $key into the app link');
        expect(c['web_link'], isNot(contains('$key=')),
            reason: '${c['type']} leaked $key into the web link');
      }
    }
    // Sanity: the split-bill case really did carry those fields in its payload,
    // so the assertion above had something to catch.
    final sb = fixture
        .firstWhere((e) => (e as Map)['type'] == 'split_bill.reminder') as Map;
    expect((sb['data'] as Map)['amount'], isNotNull);
  });

  test('the ids added at creation reach the exact record', () {
    NotificationTarget? of(String type) =>
        NotificationRouteResolver.resolveUri(Uri.parse(
            fixture.firstWhere((e) => (e as Map)['type'] == type)['app_link']
                as String));

    final splitBill = of('split_bill.reminder');
    expect(splitBill!.route, AppRoutes.splitBillDetail);
    expect(splitBill.precision, TargetPrecision.record);

    // The generic entity_id alone is enough — this case carries no
    // split_bill_id, which is the shape a handler emits after adopting it.
    final created = of('split_bill.created');
    expect(created!.route, AppRoutes.splitBillDetail);
    expect(created.precision, TargetPrecision.record);

    expect(of('invoice')!.route, AppRoutes.invoiceDetails);
    expect(of('invoice')!.precision, TargetPrecision.record);

    expect(of('giftcard')!.route, AppRoutes.giftCardFromReference);
    expect(of('giftcard')!.precision, TargetPrecision.record);

    expect(of('recurring_transfer_auto_paused')!.route,
        AppRoutes.recurringTransferDetail);

    expect(of('p2p_message')!.route, AppRoutes.p2pChat);
    expect(of('security')!.route, AppRoutes.transactionPinSetup);
  });
}
