// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: payments.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentsService_SendFunds_FullMethodName                        = "/payments.PaymentsService/SendFunds"
	PaymentsService_BatchTransfer_FullMethodName                    = "/payments.PaymentsService/BatchTransfer"
	PaymentsService_Withdraw_FullMethodName                         = "/payments.PaymentsService/Withdraw"
	PaymentsService_Deposit_FullMethodName                          = "/payments.PaymentsService/Deposit"
	PaymentsService_PayWithTag_FullMethodName                       = "/payments.PaymentsService/PayWithTag"
	PaymentsService_PayElectricityBill_FullMethodName               = "/payments.PaymentsService/PayElectricityBill"
	PaymentsService_BuyAirtime_FullMethodName                       = "/payments.PaymentsService/BuyAirtime"
	PaymentsService_BarcodePay_FullMethodName                       = "/payments.PaymentsService/BarcodePay"
	PaymentsService_ScanToPay_FullMethodName                        = "/payments.PaymentsService/ScanToPay"
	PaymentsService_GetPaymentHistory_FullMethodName                = "/payments.PaymentsService/GetPaymentHistory"
	PaymentsService_GetBillProviders_FullMethodName                 = "/payments.PaymentsService/GetBillProviders"
	PaymentsService_GetAirtimeProviders_FullMethodName              = "/payments.PaymentsService/GetAirtimeProviders"
	PaymentsService_PayWithBankDetails_FullMethodName               = "/payments.PaymentsService/PayWithBankDetails"
	PaymentsService_ResolveTag_FullMethodName                       = "/payments.PaymentsService/ResolveTag"
	PaymentsService_VerifyBankAccount_FullMethodName                = "/payments.PaymentsService/VerifyBankAccount"
	PaymentsService_InitiateDomesticTransfer_FullMethodName         = "/payments.PaymentsService/InitiateDomesticTransfer"
	PaymentsService_InitiateInternalTransfer_FullMethodName         = "/payments.PaymentsService/InitiateInternalTransfer"
	PaymentsService_InitiateInternationalTransfer_FullMethodName    = "/payments.PaymentsService/InitiateInternationalTransfer"
	PaymentsService_InitiateUserTransfer_FullMethodName             = "/payments.PaymentsService/InitiateUserTransfer"
	PaymentsService_InitiatePhoneTransfer_FullMethodName            = "/payments.PaymentsService/InitiatePhoneTransfer"
	PaymentsService_GetTransferStatus_FullMethodName                = "/payments.PaymentsService/GetTransferStatus"
	PaymentsService_GetUserTransfers_FullMethodName                 = "/payments.PaymentsService/GetUserTransfers"
	PaymentsService_GetTransferFee_FullMethodName                   = "/payments.PaymentsService/GetTransferFee"
	PaymentsService_GetDailyUsage_FullMethodName                    = "/payments.PaymentsService/GetDailyUsage"
	PaymentsService_GetExchangeRate_FullMethodName                  = "/payments.PaymentsService/GetExchangeRate"
	PaymentsService_HandleTransferWebhook_FullMethodName            = "/payments.PaymentsService/HandleTransferWebhook"
	PaymentsService_PayPlatformFee_FullMethodName                   = "/payments.PaymentsService/PayPlatformFee"
	PaymentsService_RefundFromPlatformWallet_FullMethodName         = "/payments.PaymentsService/RefundFromPlatformWallet"
	PaymentsService_GenerateQRPaymentToken_FullMethodName           = "/payments.PaymentsService/GenerateQRPaymentToken"
	PaymentsService_ValidateQRPaymentToken_FullMethodName           = "/payments.PaymentsService/ValidateQRPaymentToken"
	PaymentsService_GetBatchTransfers_FullMethodName                = "/payments.PaymentsService/GetBatchTransfers"
	PaymentsService_GetBatchTransferDetail_FullMethodName           = "/payments.PaymentsService/GetBatchTransferDetail"
	PaymentsService_VerifyMultiCountryIdentity_FullMethodName       = "/payments.PaymentsService/VerifyMultiCountryIdentity"
	PaymentsService_GetIdentityVerificationStatus_FullMethodName    = "/payments.PaymentsService/GetIdentityVerificationStatus"
	PaymentsService_CreateRecurringTransfer_FullMethodName          = "/payments.PaymentsService/CreateRecurringTransfer"
	PaymentsService_GetRecurringTransfers_FullMethodName            = "/payments.PaymentsService/GetRecurringTransfers"
	PaymentsService_GetRecurringTransfer_FullMethodName             = "/payments.PaymentsService/GetRecurringTransfer"
	PaymentsService_UpdateRecurringTransfer_FullMethodName          = "/payments.PaymentsService/UpdateRecurringTransfer"
	PaymentsService_DeleteRecurringTransfer_FullMethodName          = "/payments.PaymentsService/DeleteRecurringTransfer"
	PaymentsService_GetRecurringTransferExecutions_FullMethodName   = "/payments.PaymentsService/GetRecurringTransferExecutions"
	PaymentsService_GetRecurringTransfersByRecipient_FullMethodName = "/payments.PaymentsService/GetRecurringTransfersByRecipient"
)

// PaymentsServiceClient is the client API for PaymentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Payments Service - All payment and transfer operations
type PaymentsServiceClient interface {
	// Transfer funds to another account (sendFunds from AppServiceName)
	SendFunds(ctx context.Context, in *SendFundsRequest, opts ...grpc.CallOption) (*SendFundsResponse, error)
	// Batch transfer to multiple recipients (batchTransfer from AppServiceName)
	BatchTransfer(ctx context.Context, in *BatchTransferRequest, opts ...grpc.CallOption) (*BatchTransferResponse, error)
	// Withdraw cash from account
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	// Deposit cash to account
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	// Pay using tag/username (tagPay from AppServiceName)
	PayWithTag(ctx context.Context, in *PayWithTagRequest, opts ...grpc.CallOption) (*PayWithTagResponse, error)
	// Pay electricity bill (payElectricityBill from AppServiceName)
	PayElectricityBill(ctx context.Context, in *PayElectricityBillRequest, opts ...grpc.CallOption) (*PayElectricityBillResponse, error)
	// Buy airtime/data (airtime from AppServiceName)
	BuyAirtime(ctx context.Context, in *BuyAirtimeRequest, opts ...grpc.CallOption) (*BuyAirtimeResponse, error)
	// Pay by scanning barcode (barcodeQuickPay from AppServiceName)
	BarcodePay(ctx context.Context, in *BarcodePayRequest, opts ...grpc.CallOption) (*BarcodePayResponse, error)
	// AI-powered scan to pay (aiScanToPay from AppServiceName)
	ScanToPay(ctx context.Context, in *ScanToPayRequest, opts ...grpc.CallOption) (*ScanToPayResponse, error)
	// Get payment history
	GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error)
	// Get bill providers
	GetBillProviders(ctx context.Context, in *GetBillProvidersRequest, opts ...grpc.CallOption) (*GetBillProvidersResponse, error)
	// Get airtime providers
	GetAirtimeProviders(ctx context.Context, in *GetAirtimeProvidersRequest, opts ...grpc.CallOption) (*GetAirtimeProvidersResponse, error)
	// Pay using scanned bank details (scan-to-pay feature)
	PayWithBankDetails(ctx context.Context, in *PayWithBankDetailsRequest, opts ...grpc.CallOption) (*PayWithBankDetailsResponse, error)
	// Resolve tag to account
	ResolveTag(ctx context.Context, in *ResolveTagRequest, opts ...grpc.CallOption) (*ResolveTagResponse, error)
	// Verify bank account details (Lemfi-style verification)
	VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error)
	InitiateDomesticTransfer(ctx context.Context, in *InitiateDomesticTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	InitiateInternalTransfer(ctx context.Context, in *InitiateInternalTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	InitiateInternationalTransfer(ctx context.Context, in *InitiateInternationalTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	InitiateUserTransfer(ctx context.Context, in *InitiateUserTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	InitiatePhoneTransfer(ctx context.Context, in *InitiatePhoneTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*GetTransferStatusResponse, error)
	GetUserTransfers(ctx context.Context, in *GetUserTransfersRequest, opts ...grpc.CallOption) (*GetUserTransfersResponse, error)
	GetTransferFee(ctx context.Context, in *GetTransferFeeRequest, opts ...grpc.CallOption) (*GetTransferFeeResponse, error)
	GetDailyUsage(ctx context.Context, in *GetDailyUsageRequest, opts ...grpc.CallOption) (*GetDailyUsageResponse, error)
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateResponse, error)
	HandleTransferWebhook(ctx context.Context, in *HandleTransferWebhookRequest, opts ...grpc.CallOption) (*HandleTransferWebhookResponse, error)
	// PayPlatformFee - Debit user account, credit platform revenue wallet
	PayPlatformFee(ctx context.Context, in *PayPlatformFeeRequest, opts ...grpc.CallOption) (*PayPlatformFeeResponse, error)
	// RefundFromPlatformWallet - Refund from platform wallet to user account
	RefundFromPlatformWallet(ctx context.Context, in *RefundFromPlatformWalletRequest, opts ...grpc.CallOption) (*RefundFromPlatformWalletResponse, error)
	// Generate a QR payment token for receiving payments
	GenerateQRPaymentToken(ctx context.Context, in *GenerateQRTokenRequest, opts ...grpc.CallOption) (*GenerateQRTokenResponse, error)
	// Validate a QR payment token before initiating transfer
	ValidateQRPaymentToken(ctx context.Context, in *ValidateQRTokenRequest, opts ...grpc.CallOption) (*ValidateQRTokenResponse, error)
	GetBatchTransfers(ctx context.Context, in *GetBatchTransfersRequest, opts ...grpc.CallOption) (*GetBatchTransfersResponse, error)
	GetBatchTransferDetail(ctx context.Context, in *GetBatchTransferDetailRequest, opts ...grpc.CallOption) (*GetBatchTransferDetailResponse, error)
	// Verify identity using country-specific provider (Smile ID, Onfido, Persona)
	VerifyMultiCountryIdentity(ctx context.Context, in *VerifyMultiCountryIdentityRequest, opts ...grpc.CallOption) (*VerifyMultiCountryIdentityResponse, error)
	// Get status of an async identity verification (Onfido/Persona)
	GetIdentityVerificationStatus(ctx context.Context, in *GetKYCVerificationStatusRequest, opts ...grpc.CallOption) (*GetKYCVerificationStatusResponse, error)
	// Create a recurring transfer rule
	CreateRecurringTransfer(ctx context.Context, in *CreateRecurringTransferRequest, opts ...grpc.CallOption) (*CreateRecurringTransferResponse, error)
	// List user's recurring transfers
	GetRecurringTransfers(ctx context.Context, in *GetRecurringTransfersRequest, opts ...grpc.CallOption) (*GetRecurringTransfersResponse, error)
	// Get single recurring transfer detail
	GetRecurringTransfer(ctx context.Context, in *GetRecurringTransferRequest, opts ...grpc.CallOption) (*GetRecurringTransferResponse, error)
	// Update a recurring transfer (pause, resume, edit)
	UpdateRecurringTransfer(ctx context.Context, in *UpdateRecurringTransferRequest, opts ...grpc.CallOption) (*UpdateRecurringTransferResponse, error)
	// Cancel a recurring transfer
	DeleteRecurringTransfer(ctx context.Context, in *DeleteRecurringTransferRequest, opts ...grpc.CallOption) (*DeleteRecurringTransferResponse, error)
	// Get execution history for a recurring transfer
	GetRecurringTransferExecutions(ctx context.Context, in *GetRecurringTransferExecutionsRequest, opts ...grpc.CallOption) (*GetRecurringTransferExecutionsResponse, error)
	// Get recurring transfers by recipient (for badge display)
	GetRecurringTransfersByRecipient(ctx context.Context, in *GetRecurringTransfersByRecipientRequest, opts ...grpc.CallOption) (*GetRecurringTransfersByRecipientResponse, error)
}

type paymentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsServiceClient(cc grpc.ClientConnInterface) PaymentsServiceClient {
	return &paymentsServiceClient{cc}
}

func (c *paymentsServiceClient) SendFunds(ctx context.Context, in *SendFundsRequest, opts ...grpc.CallOption) (*SendFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFundsResponse)
	err := c.cc.Invoke(ctx, PaymentsService_SendFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) BatchTransfer(ctx context.Context, in *BatchTransferRequest, opts ...grpc.CallOption) (*BatchTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_BatchTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, PaymentsService_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, PaymentsService_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) PayWithTag(ctx context.Context, in *PayWithTagRequest, opts ...grpc.CallOption) (*PayWithTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayWithTagResponse)
	err := c.cc.Invoke(ctx, PaymentsService_PayWithTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) PayElectricityBill(ctx context.Context, in *PayElectricityBillRequest, opts ...grpc.CallOption) (*PayElectricityBillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayElectricityBillResponse)
	err := c.cc.Invoke(ctx, PaymentsService_PayElectricityBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) BuyAirtime(ctx context.Context, in *BuyAirtimeRequest, opts ...grpc.CallOption) (*BuyAirtimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyAirtimeResponse)
	err := c.cc.Invoke(ctx, PaymentsService_BuyAirtime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) BarcodePay(ctx context.Context, in *BarcodePayRequest, opts ...grpc.CallOption) (*BarcodePayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BarcodePayResponse)
	err := c.cc.Invoke(ctx, PaymentsService_BarcodePay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) ScanToPay(ctx context.Context, in *ScanToPayRequest, opts ...grpc.CallOption) (*ScanToPayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanToPayResponse)
	err := c.cc.Invoke(ctx, PaymentsService_ScanToPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentHistoryResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetPaymentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetBillProviders(ctx context.Context, in *GetBillProvidersRequest, opts ...grpc.CallOption) (*GetBillProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillProvidersResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetBillProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetAirtimeProviders(ctx context.Context, in *GetAirtimeProvidersRequest, opts ...grpc.CallOption) (*GetAirtimeProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAirtimeProvidersResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetAirtimeProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) PayWithBankDetails(ctx context.Context, in *PayWithBankDetailsRequest, opts ...grpc.CallOption) (*PayWithBankDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayWithBankDetailsResponse)
	err := c.cc.Invoke(ctx, PaymentsService_PayWithBankDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) ResolveTag(ctx context.Context, in *ResolveTagRequest, opts ...grpc.CallOption) (*ResolveTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTagResponse)
	err := c.cc.Invoke(ctx, PaymentsService_ResolveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBankAccountResponse)
	err := c.cc.Invoke(ctx, PaymentsService_VerifyBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) InitiateDomesticTransfer(ctx context.Context, in *InitiateDomesticTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_InitiateDomesticTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) InitiateInternalTransfer(ctx context.Context, in *InitiateInternalTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_InitiateInternalTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) InitiateInternationalTransfer(ctx context.Context, in *InitiateInternationalTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_InitiateInternationalTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) InitiateUserTransfer(ctx context.Context, in *InitiateUserTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_InitiateUserTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) InitiatePhoneTransfer(ctx context.Context, in *InitiatePhoneTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_InitiatePhoneTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*GetTransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransferStatusResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetUserTransfers(ctx context.Context, in *GetUserTransfersRequest, opts ...grpc.CallOption) (*GetUserTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTransfersResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetUserTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetTransferFee(ctx context.Context, in *GetTransferFeeRequest, opts ...grpc.CallOption) (*GetTransferFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransferFeeResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetTransferFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetDailyUsage(ctx context.Context, in *GetDailyUsageRequest, opts ...grpc.CallOption) (*GetDailyUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyUsageResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetDailyUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExchangeRateResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) HandleTransferWebhook(ctx context.Context, in *HandleTransferWebhookRequest, opts ...grpc.CallOption) (*HandleTransferWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleTransferWebhookResponse)
	err := c.cc.Invoke(ctx, PaymentsService_HandleTransferWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) PayPlatformFee(ctx context.Context, in *PayPlatformFeeRequest, opts ...grpc.CallOption) (*PayPlatformFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayPlatformFeeResponse)
	err := c.cc.Invoke(ctx, PaymentsService_PayPlatformFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) RefundFromPlatformWallet(ctx context.Context, in *RefundFromPlatformWalletRequest, opts ...grpc.CallOption) (*RefundFromPlatformWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundFromPlatformWalletResponse)
	err := c.cc.Invoke(ctx, PaymentsService_RefundFromPlatformWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GenerateQRPaymentToken(ctx context.Context, in *GenerateQRTokenRequest, opts ...grpc.CallOption) (*GenerateQRTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQRTokenResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GenerateQRPaymentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) ValidateQRPaymentToken(ctx context.Context, in *ValidateQRTokenRequest, opts ...grpc.CallOption) (*ValidateQRTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateQRTokenResponse)
	err := c.cc.Invoke(ctx, PaymentsService_ValidateQRPaymentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetBatchTransfers(ctx context.Context, in *GetBatchTransfersRequest, opts ...grpc.CallOption) (*GetBatchTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchTransfersResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetBatchTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetBatchTransferDetail(ctx context.Context, in *GetBatchTransferDetailRequest, opts ...grpc.CallOption) (*GetBatchTransferDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchTransferDetailResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetBatchTransferDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) VerifyMultiCountryIdentity(ctx context.Context, in *VerifyMultiCountryIdentityRequest, opts ...grpc.CallOption) (*VerifyMultiCountryIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyMultiCountryIdentityResponse)
	err := c.cc.Invoke(ctx, PaymentsService_VerifyMultiCountryIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetIdentityVerificationStatus(ctx context.Context, in *GetKYCVerificationStatusRequest, opts ...grpc.CallOption) (*GetKYCVerificationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCVerificationStatusResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetIdentityVerificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) CreateRecurringTransfer(ctx context.Context, in *CreateRecurringTransferRequest, opts ...grpc.CallOption) (*CreateRecurringTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecurringTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_CreateRecurringTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetRecurringTransfers(ctx context.Context, in *GetRecurringTransfersRequest, opts ...grpc.CallOption) (*GetRecurringTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecurringTransfersResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetRecurringTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetRecurringTransfer(ctx context.Context, in *GetRecurringTransferRequest, opts ...grpc.CallOption) (*GetRecurringTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecurringTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetRecurringTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) UpdateRecurringTransfer(ctx context.Context, in *UpdateRecurringTransferRequest, opts ...grpc.CallOption) (*UpdateRecurringTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRecurringTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_UpdateRecurringTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) DeleteRecurringTransfer(ctx context.Context, in *DeleteRecurringTransferRequest, opts ...grpc.CallOption) (*DeleteRecurringTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecurringTransferResponse)
	err := c.cc.Invoke(ctx, PaymentsService_DeleteRecurringTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetRecurringTransferExecutions(ctx context.Context, in *GetRecurringTransferExecutionsRequest, opts ...grpc.CallOption) (*GetRecurringTransferExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecurringTransferExecutionsResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetRecurringTransferExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) GetRecurringTransfersByRecipient(ctx context.Context, in *GetRecurringTransfersByRecipientRequest, opts ...grpc.CallOption) (*GetRecurringTransfersByRecipientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecurringTransfersByRecipientResponse)
	err := c.cc.Invoke(ctx, PaymentsService_GetRecurringTransfersByRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServiceServer is the server API for PaymentsService service.
// All implementations must embed UnimplementedPaymentsServiceServer
// for forward compatibility.
//
// Payments Service - All payment and transfer operations
type PaymentsServiceServer interface {
	// Transfer funds to another account (sendFunds from AppServiceName)
	SendFunds(context.Context, *SendFundsRequest) (*SendFundsResponse, error)
	// Batch transfer to multiple recipients (batchTransfer from AppServiceName)
	BatchTransfer(context.Context, *BatchTransferRequest) (*BatchTransferResponse, error)
	// Withdraw cash from account
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	// Deposit cash to account
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	// Pay using tag/username (tagPay from AppServiceName)
	PayWithTag(context.Context, *PayWithTagRequest) (*PayWithTagResponse, error)
	// Pay electricity bill (payElectricityBill from AppServiceName)
	PayElectricityBill(context.Context, *PayElectricityBillRequest) (*PayElectricityBillResponse, error)
	// Buy airtime/data (airtime from AppServiceName)
	BuyAirtime(context.Context, *BuyAirtimeRequest) (*BuyAirtimeResponse, error)
	// Pay by scanning barcode (barcodeQuickPay from AppServiceName)
	BarcodePay(context.Context, *BarcodePayRequest) (*BarcodePayResponse, error)
	// AI-powered scan to pay (aiScanToPay from AppServiceName)
	ScanToPay(context.Context, *ScanToPayRequest) (*ScanToPayResponse, error)
	// Get payment history
	GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error)
	// Get bill providers
	GetBillProviders(context.Context, *GetBillProvidersRequest) (*GetBillProvidersResponse, error)
	// Get airtime providers
	GetAirtimeProviders(context.Context, *GetAirtimeProvidersRequest) (*GetAirtimeProvidersResponse, error)
	// Pay using scanned bank details (scan-to-pay feature)
	PayWithBankDetails(context.Context, *PayWithBankDetailsRequest) (*PayWithBankDetailsResponse, error)
	// Resolve tag to account
	ResolveTag(context.Context, *ResolveTagRequest) (*ResolveTagResponse, error)
	// Verify bank account details (Lemfi-style verification)
	VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error)
	InitiateDomesticTransfer(context.Context, *InitiateDomesticTransferRequest) (*InitiateTransferResponse, error)
	InitiateInternalTransfer(context.Context, *InitiateInternalTransferRequest) (*InitiateTransferResponse, error)
	InitiateInternationalTransfer(context.Context, *InitiateInternationalTransferRequest) (*InitiateTransferResponse, error)
	InitiateUserTransfer(context.Context, *InitiateUserTransferRequest) (*InitiateTransferResponse, error)
	InitiatePhoneTransfer(context.Context, *InitiatePhoneTransferRequest) (*InitiateTransferResponse, error)
	GetTransferStatus(context.Context, *GetTransferStatusRequest) (*GetTransferStatusResponse, error)
	GetUserTransfers(context.Context, *GetUserTransfersRequest) (*GetUserTransfersResponse, error)
	GetTransferFee(context.Context, *GetTransferFeeRequest) (*GetTransferFeeResponse, error)
	GetDailyUsage(context.Context, *GetDailyUsageRequest) (*GetDailyUsageResponse, error)
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateResponse, error)
	HandleTransferWebhook(context.Context, *HandleTransferWebhookRequest) (*HandleTransferWebhookResponse, error)
	// PayPlatformFee - Debit user account, credit platform revenue wallet
	PayPlatformFee(context.Context, *PayPlatformFeeRequest) (*PayPlatformFeeResponse, error)
	// RefundFromPlatformWallet - Refund from platform wallet to user account
	RefundFromPlatformWallet(context.Context, *RefundFromPlatformWalletRequest) (*RefundFromPlatformWalletResponse, error)
	// Generate a QR payment token for receiving payments
	GenerateQRPaymentToken(context.Context, *GenerateQRTokenRequest) (*GenerateQRTokenResponse, error)
	// Validate a QR payment token before initiating transfer
	ValidateQRPaymentToken(context.Context, *ValidateQRTokenRequest) (*ValidateQRTokenResponse, error)
	GetBatchTransfers(context.Context, *GetBatchTransfersRequest) (*GetBatchTransfersResponse, error)
	GetBatchTransferDetail(context.Context, *GetBatchTransferDetailRequest) (*GetBatchTransferDetailResponse, error)
	// Verify identity using country-specific provider (Smile ID, Onfido, Persona)
	VerifyMultiCountryIdentity(context.Context, *VerifyMultiCountryIdentityRequest) (*VerifyMultiCountryIdentityResponse, error)
	// Get status of an async identity verification (Onfido/Persona)
	GetIdentityVerificationStatus(context.Context, *GetKYCVerificationStatusRequest) (*GetKYCVerificationStatusResponse, error)
	// Create a recurring transfer rule
	CreateRecurringTransfer(context.Context, *CreateRecurringTransferRequest) (*CreateRecurringTransferResponse, error)
	// List user's recurring transfers
	GetRecurringTransfers(context.Context, *GetRecurringTransfersRequest) (*GetRecurringTransfersResponse, error)
	// Get single recurring transfer detail
	GetRecurringTransfer(context.Context, *GetRecurringTransferRequest) (*GetRecurringTransferResponse, error)
	// Update a recurring transfer (pause, resume, edit)
	UpdateRecurringTransfer(context.Context, *UpdateRecurringTransferRequest) (*UpdateRecurringTransferResponse, error)
	// Cancel a recurring transfer
	DeleteRecurringTransfer(context.Context, *DeleteRecurringTransferRequest) (*DeleteRecurringTransferResponse, error)
	// Get execution history for a recurring transfer
	GetRecurringTransferExecutions(context.Context, *GetRecurringTransferExecutionsRequest) (*GetRecurringTransferExecutionsResponse, error)
	// Get recurring transfers by recipient (for badge display)
	GetRecurringTransfersByRecipient(context.Context, *GetRecurringTransfersByRecipientRequest) (*GetRecurringTransfersByRecipientResponse, error)
	mustEmbedUnimplementedPaymentsServiceServer()
}

// UnimplementedPaymentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentsServiceServer struct{}

func (UnimplementedPaymentsServiceServer) SendFunds(context.Context, *SendFundsRequest) (*SendFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFunds not implemented")
}
func (UnimplementedPaymentsServiceServer) BatchTransfer(context.Context, *BatchTransferRequest) (*BatchTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedPaymentsServiceServer) Deposit(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedPaymentsServiceServer) PayWithTag(context.Context, *PayWithTagRequest) (*PayWithTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayWithTag not implemented")
}
func (UnimplementedPaymentsServiceServer) PayElectricityBill(context.Context, *PayElectricityBillRequest) (*PayElectricityBillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayElectricityBill not implemented")
}
func (UnimplementedPaymentsServiceServer) BuyAirtime(context.Context, *BuyAirtimeRequest) (*BuyAirtimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuyAirtime not implemented")
}
func (UnimplementedPaymentsServiceServer) BarcodePay(context.Context, *BarcodePayRequest) (*BarcodePayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BarcodePay not implemented")
}
func (UnimplementedPaymentsServiceServer) ScanToPay(context.Context, *ScanToPayRequest) (*ScanToPayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanToPay not implemented")
}
func (UnimplementedPaymentsServiceServer) GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentHistory not implemented")
}
func (UnimplementedPaymentsServiceServer) GetBillProviders(context.Context, *GetBillProvidersRequest) (*GetBillProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBillProviders not implemented")
}
func (UnimplementedPaymentsServiceServer) GetAirtimeProviders(context.Context, *GetAirtimeProvidersRequest) (*GetAirtimeProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAirtimeProviders not implemented")
}
func (UnimplementedPaymentsServiceServer) PayWithBankDetails(context.Context, *PayWithBankDetailsRequest) (*PayWithBankDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayWithBankDetails not implemented")
}
func (UnimplementedPaymentsServiceServer) ResolveTag(context.Context, *ResolveTagRequest) (*ResolveTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveTag not implemented")
}
func (UnimplementedPaymentsServiceServer) VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyBankAccount not implemented")
}
func (UnimplementedPaymentsServiceServer) InitiateDomesticTransfer(context.Context, *InitiateDomesticTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateDomesticTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) InitiateInternalTransfer(context.Context, *InitiateInternalTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateInternalTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) InitiateInternationalTransfer(context.Context, *InitiateInternationalTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateInternationalTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) InitiateUserTransfer(context.Context, *InitiateUserTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateUserTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) InitiatePhoneTransfer(context.Context, *InitiatePhoneTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiatePhoneTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) GetTransferStatus(context.Context, *GetTransferStatusRequest) (*GetTransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedPaymentsServiceServer) GetUserTransfers(context.Context, *GetUserTransfersRequest) (*GetUserTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTransfers not implemented")
}
func (UnimplementedPaymentsServiceServer) GetTransferFee(context.Context, *GetTransferFeeRequest) (*GetTransferFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferFee not implemented")
}
func (UnimplementedPaymentsServiceServer) GetDailyUsage(context.Context, *GetDailyUsageRequest) (*GetDailyUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyUsage not implemented")
}
func (UnimplementedPaymentsServiceServer) GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedPaymentsServiceServer) HandleTransferWebhook(context.Context, *HandleTransferWebhookRequest) (*HandleTransferWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleTransferWebhook not implemented")
}
func (UnimplementedPaymentsServiceServer) PayPlatformFee(context.Context, *PayPlatformFeeRequest) (*PayPlatformFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayPlatformFee not implemented")
}
func (UnimplementedPaymentsServiceServer) RefundFromPlatformWallet(context.Context, *RefundFromPlatformWalletRequest) (*RefundFromPlatformWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundFromPlatformWallet not implemented")
}
func (UnimplementedPaymentsServiceServer) GenerateQRPaymentToken(context.Context, *GenerateQRTokenRequest) (*GenerateQRTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQRPaymentToken not implemented")
}
func (UnimplementedPaymentsServiceServer) ValidateQRPaymentToken(context.Context, *ValidateQRTokenRequest) (*ValidateQRTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateQRPaymentToken not implemented")
}
func (UnimplementedPaymentsServiceServer) GetBatchTransfers(context.Context, *GetBatchTransfersRequest) (*GetBatchTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchTransfers not implemented")
}
func (UnimplementedPaymentsServiceServer) GetBatchTransferDetail(context.Context, *GetBatchTransferDetailRequest) (*GetBatchTransferDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchTransferDetail not implemented")
}
func (UnimplementedPaymentsServiceServer) VerifyMultiCountryIdentity(context.Context, *VerifyMultiCountryIdentityRequest) (*VerifyMultiCountryIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyMultiCountryIdentity not implemented")
}
func (UnimplementedPaymentsServiceServer) GetIdentityVerificationStatus(context.Context, *GetKYCVerificationStatusRequest) (*GetKYCVerificationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityVerificationStatus not implemented")
}
func (UnimplementedPaymentsServiceServer) CreateRecurringTransfer(context.Context, *CreateRecurringTransferRequest) (*CreateRecurringTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecurringTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) GetRecurringTransfers(context.Context, *GetRecurringTransfersRequest) (*GetRecurringTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecurringTransfers not implemented")
}
func (UnimplementedPaymentsServiceServer) GetRecurringTransfer(context.Context, *GetRecurringTransferRequest) (*GetRecurringTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecurringTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) UpdateRecurringTransfer(context.Context, *UpdateRecurringTransferRequest) (*UpdateRecurringTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecurringTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) DeleteRecurringTransfer(context.Context, *DeleteRecurringTransferRequest) (*DeleteRecurringTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecurringTransfer not implemented")
}
func (UnimplementedPaymentsServiceServer) GetRecurringTransferExecutions(context.Context, *GetRecurringTransferExecutionsRequest) (*GetRecurringTransferExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecurringTransferExecutions not implemented")
}
func (UnimplementedPaymentsServiceServer) GetRecurringTransfersByRecipient(context.Context, *GetRecurringTransfersByRecipientRequest) (*GetRecurringTransfersByRecipientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecurringTransfersByRecipient not implemented")
}
func (UnimplementedPaymentsServiceServer) mustEmbedUnimplementedPaymentsServiceServer() {}
func (UnimplementedPaymentsServiceServer) testEmbeddedByValue()                         {}

// UnsafePaymentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServiceServer will
// result in compilation errors.
type UnsafePaymentsServiceServer interface {
	mustEmbedUnimplementedPaymentsServiceServer()
}

func RegisterPaymentsServiceServer(s grpc.ServiceRegistrar, srv PaymentsServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentsService_ServiceDesc, srv)
}

func _PaymentsService_SendFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).SendFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_SendFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).SendFunds(ctx, req.(*SendFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_BatchTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).BatchTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_BatchTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).BatchTransfer(ctx, req.(*BatchTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_PayWithTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayWithTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).PayWithTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_PayWithTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).PayWithTag(ctx, req.(*PayWithTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_PayElectricityBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayElectricityBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).PayElectricityBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_PayElectricityBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).PayElectricityBill(ctx, req.(*PayElectricityBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_BuyAirtime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyAirtimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).BuyAirtime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_BuyAirtime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).BuyAirtime(ctx, req.(*BuyAirtimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_BarcodePay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarcodePayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).BarcodePay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_BarcodePay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).BarcodePay(ctx, req.(*BarcodePayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_ScanToPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanToPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).ScanToPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_ScanToPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).ScanToPay(ctx, req.(*ScanToPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetPaymentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetPaymentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetPaymentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetPaymentHistory(ctx, req.(*GetPaymentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetBillProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetBillProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetBillProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetBillProviders(ctx, req.(*GetBillProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetAirtimeProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirtimeProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetAirtimeProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetAirtimeProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetAirtimeProviders(ctx, req.(*GetAirtimeProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_PayWithBankDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayWithBankDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).PayWithBankDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_PayWithBankDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).PayWithBankDetails(ctx, req.(*PayWithBankDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_ResolveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).ResolveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_ResolveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).ResolveTag(ctx, req.(*ResolveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_VerifyBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).VerifyBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_VerifyBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).VerifyBankAccount(ctx, req.(*VerifyBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_InitiateDomesticTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateDomesticTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).InitiateDomesticTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_InitiateDomesticTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).InitiateDomesticTransfer(ctx, req.(*InitiateDomesticTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_InitiateInternalTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateInternalTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).InitiateInternalTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_InitiateInternalTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).InitiateInternalTransfer(ctx, req.(*InitiateInternalTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_InitiateInternationalTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateInternationalTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).InitiateInternationalTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_InitiateInternationalTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).InitiateInternationalTransfer(ctx, req.(*InitiateInternationalTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_InitiateUserTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateUserTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).InitiateUserTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_InitiateUserTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).InitiateUserTransfer(ctx, req.(*InitiateUserTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_InitiatePhoneTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatePhoneTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).InitiatePhoneTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_InitiatePhoneTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).InitiatePhoneTransfer(ctx, req.(*InitiatePhoneTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetTransferStatus(ctx, req.(*GetTransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetUserTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetUserTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetUserTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetUserTransfers(ctx, req.(*GetUserTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetTransferFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetTransferFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetTransferFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetTransferFee(ctx, req.(*GetTransferFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetDailyUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetDailyUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetDailyUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetDailyUsage(ctx, req.(*GetDailyUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_HandleTransferWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTransferWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).HandleTransferWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_HandleTransferWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).HandleTransferWebhook(ctx, req.(*HandleTransferWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_PayPlatformFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayPlatformFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).PayPlatformFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_PayPlatformFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).PayPlatformFee(ctx, req.(*PayPlatformFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_RefundFromPlatformWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundFromPlatformWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).RefundFromPlatformWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_RefundFromPlatformWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).RefundFromPlatformWallet(ctx, req.(*RefundFromPlatformWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GenerateQRPaymentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQRTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GenerateQRPaymentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GenerateQRPaymentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GenerateQRPaymentToken(ctx, req.(*GenerateQRTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_ValidateQRPaymentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQRTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).ValidateQRPaymentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_ValidateQRPaymentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).ValidateQRPaymentToken(ctx, req.(*ValidateQRTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetBatchTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetBatchTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetBatchTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetBatchTransfers(ctx, req.(*GetBatchTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetBatchTransferDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchTransferDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetBatchTransferDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetBatchTransferDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetBatchTransferDetail(ctx, req.(*GetBatchTransferDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_VerifyMultiCountryIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMultiCountryIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).VerifyMultiCountryIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_VerifyMultiCountryIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).VerifyMultiCountryIdentity(ctx, req.(*VerifyMultiCountryIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetIdentityVerificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCVerificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetIdentityVerificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetIdentityVerificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetIdentityVerificationStatus(ctx, req.(*GetKYCVerificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_CreateRecurringTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecurringTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).CreateRecurringTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_CreateRecurringTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).CreateRecurringTransfer(ctx, req.(*CreateRecurringTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetRecurringTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecurringTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetRecurringTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetRecurringTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetRecurringTransfers(ctx, req.(*GetRecurringTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetRecurringTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecurringTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetRecurringTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetRecurringTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetRecurringTransfer(ctx, req.(*GetRecurringTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_UpdateRecurringTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecurringTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).UpdateRecurringTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_UpdateRecurringTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).UpdateRecurringTransfer(ctx, req.(*UpdateRecurringTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_DeleteRecurringTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecurringTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).DeleteRecurringTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_DeleteRecurringTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).DeleteRecurringTransfer(ctx, req.(*DeleteRecurringTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetRecurringTransferExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecurringTransferExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetRecurringTransferExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetRecurringTransferExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetRecurringTransferExecutions(ctx, req.(*GetRecurringTransferExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_GetRecurringTransfersByRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecurringTransfersByRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).GetRecurringTransfersByRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_GetRecurringTransfersByRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).GetRecurringTransfersByRecipient(ctx, req.(*GetRecurringTransfersByRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentsService_ServiceDesc is the grpc.ServiceDesc for PaymentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.PaymentsService",
	HandlerType: (*PaymentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFunds",
			Handler:    _PaymentsService_SendFunds_Handler,
		},
		{
			MethodName: "BatchTransfer",
			Handler:    _PaymentsService_BatchTransfer_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _PaymentsService_Withdraw_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _PaymentsService_Deposit_Handler,
		},
		{
			MethodName: "PayWithTag",
			Handler:    _PaymentsService_PayWithTag_Handler,
		},
		{
			MethodName: "PayElectricityBill",
			Handler:    _PaymentsService_PayElectricityBill_Handler,
		},
		{
			MethodName: "BuyAirtime",
			Handler:    _PaymentsService_BuyAirtime_Handler,
		},
		{
			MethodName: "BarcodePay",
			Handler:    _PaymentsService_BarcodePay_Handler,
		},
		{
			MethodName: "ScanToPay",
			Handler:    _PaymentsService_ScanToPay_Handler,
		},
		{
			MethodName: "GetPaymentHistory",
			Handler:    _PaymentsService_GetPaymentHistory_Handler,
		},
		{
			MethodName: "GetBillProviders",
			Handler:    _PaymentsService_GetBillProviders_Handler,
		},
		{
			MethodName: "GetAirtimeProviders",
			Handler:    _PaymentsService_GetAirtimeProviders_Handler,
		},
		{
			MethodName: "PayWithBankDetails",
			Handler:    _PaymentsService_PayWithBankDetails_Handler,
		},
		{
			MethodName: "ResolveTag",
			Handler:    _PaymentsService_ResolveTag_Handler,
		},
		{
			MethodName: "VerifyBankAccount",
			Handler:    _PaymentsService_VerifyBankAccount_Handler,
		},
		{
			MethodName: "InitiateDomesticTransfer",
			Handler:    _PaymentsService_InitiateDomesticTransfer_Handler,
		},
		{
			MethodName: "InitiateInternalTransfer",
			Handler:    _PaymentsService_InitiateInternalTransfer_Handler,
		},
		{
			MethodName: "InitiateInternationalTransfer",
			Handler:    _PaymentsService_InitiateInternationalTransfer_Handler,
		},
		{
			MethodName: "InitiateUserTransfer",
			Handler:    _PaymentsService_InitiateUserTransfer_Handler,
		},
		{
			MethodName: "InitiatePhoneTransfer",
			Handler:    _PaymentsService_InitiatePhoneTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _PaymentsService_GetTransferStatus_Handler,
		},
		{
			MethodName: "GetUserTransfers",
			Handler:    _PaymentsService_GetUserTransfers_Handler,
		},
		{
			MethodName: "GetTransferFee",
			Handler:    _PaymentsService_GetTransferFee_Handler,
		},
		{
			MethodName: "GetDailyUsage",
			Handler:    _PaymentsService_GetDailyUsage_Handler,
		},
		{
			MethodName: "GetExchangeRate",
			Handler:    _PaymentsService_GetExchangeRate_Handler,
		},
		{
			MethodName: "HandleTransferWebhook",
			Handler:    _PaymentsService_HandleTransferWebhook_Handler,
		},
		{
			MethodName: "PayPlatformFee",
			Handler:    _PaymentsService_PayPlatformFee_Handler,
		},
		{
			MethodName: "RefundFromPlatformWallet",
			Handler:    _PaymentsService_RefundFromPlatformWallet_Handler,
		},
		{
			MethodName: "GenerateQRPaymentToken",
			Handler:    _PaymentsService_GenerateQRPaymentToken_Handler,
		},
		{
			MethodName: "ValidateQRPaymentToken",
			Handler:    _PaymentsService_ValidateQRPaymentToken_Handler,
		},
		{
			MethodName: "GetBatchTransfers",
			Handler:    _PaymentsService_GetBatchTransfers_Handler,
		},
		{
			MethodName: "GetBatchTransferDetail",
			Handler:    _PaymentsService_GetBatchTransferDetail_Handler,
		},
		{
			MethodName: "VerifyMultiCountryIdentity",
			Handler:    _PaymentsService_VerifyMultiCountryIdentity_Handler,
		},
		{
			MethodName: "GetIdentityVerificationStatus",
			Handler:    _PaymentsService_GetIdentityVerificationStatus_Handler,
		},
		{
			MethodName: "CreateRecurringTransfer",
			Handler:    _PaymentsService_CreateRecurringTransfer_Handler,
		},
		{
			MethodName: "GetRecurringTransfers",
			Handler:    _PaymentsService_GetRecurringTransfers_Handler,
		},
		{
			MethodName: "GetRecurringTransfer",
			Handler:    _PaymentsService_GetRecurringTransfer_Handler,
		},
		{
			MethodName: "UpdateRecurringTransfer",
			Handler:    _PaymentsService_UpdateRecurringTransfer_Handler,
		},
		{
			MethodName: "DeleteRecurringTransfer",
			Handler:    _PaymentsService_DeleteRecurringTransfer_Handler,
		},
		{
			MethodName: "GetRecurringTransferExecutions",
			Handler:    _PaymentsService_GetRecurringTransferExecutions_Handler,
		},
		{
			MethodName: "GetRecurringTransfersByRecipient",
			Handler:    _PaymentsService_GetRecurringTransfersByRecipient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments.proto",
}
