import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

class SplitBillPdfService {
  static final _displayDateFormat = DateFormat('MMM dd, yyyy HH:mm');

  static String _currencySymbolFor(String code) {
    switch (code.toUpperCase()) {
      case 'NGN':
        return 'NGN ';
      case 'GBP':
        return 'GBP ';
      case 'EUR':
        return 'EUR ';
      case 'USD':
        return 'USD ';
      case 'ZAR':
        return 'ZAR ';
      default:
        return '$code ';
    }
  }

  static Future<File> _generateReceipt({
    required String transactionReference,
    required double amount,
    required String currency,
    required String creatorName,
    required String description,
    required int paidCount,
    required int totalParticipants,
  }) async {
    final pdf = pw.Document();
    final currencySymbol = _currencySymbolFor(currency);
    final formattedAmount = '$currencySymbol${amount.toStringAsFixed(2)}';
    final now = DateTime.now();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Center(
                child: pw.Column(
                  children: [
                    pw.Text(
                      'LazerVault',
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue800,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      'Split Bill Payment Receipt',
                      style: pw.TextStyle(
                        fontSize: 14,
                        color: PdfColors.grey600,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 24),

              // Amount
              pw.Center(
                child: pw.Text(
                  formattedAmount,
                  style: pw.TextStyle(
                    fontSize: 36,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Center(
                child: pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 12, vertical: 4),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.green50,
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  child: pw.Text(
                    'PAID',
                    style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.green800,
                    ),
                  ),
                ),
              ),
              pw.SizedBox(height: 32),

              // Details
              _buildRow('Paid to', creatorName),
              pw.SizedBox(height: 8),
              _buildRow('Reference', transactionReference),
              pw.SizedBox(height: 8),
              _buildRow('Date', _displayDateFormat.format(now)),
              pw.SizedBox(height: 8),
              _buildRow('Currency', currency),
              if (description.isNotEmpty) ...[
                pw.SizedBox(height: 8),
                _buildRow('Description', description),
              ],
              pw.SizedBox(height: 8),
              _buildRow('Progress', '$paidCount/$totalParticipants paid'),
              pw.SizedBox(height: 32),
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 16),

              // Footer
              pw.Center(
                child: pw.Text(
                  'Generated by LazerVault',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey500,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final safeRef =
        transactionReference.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
    final file = File('${output.path}/split_bill_receipt_$safeRef.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildRow(String label, String value) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 12,
            color: PdfColors.grey700,
          ),
        ),
        pw.Flexible(
          child: pw.Text(
            value,
            textAlign: pw.TextAlign.right,
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
      ],
    );
  }

  static Future<String> downloadReceipt({
    required String transactionReference,
    required double amount,
    required String currency,
    required String creatorName,
    required String description,
    required int paidCount,
    required int totalParticipants,
  }) async {
    final file = await _generateReceipt(
      transactionReference: transactionReference,
      amount: amount,
      currency: currency,
      creatorName: creatorName,
      description: description,
      paidCount: paidCount,
      totalParticipants: totalParticipants,
    );

    Directory? directory;
    if (Platform.isAndroid) {
      directory = Directory('/storage/emulated/0/Download');
      if (!await directory.exists()) {
        directory = await getExternalStorageDirectory();
      }
    } else if (Platform.isIOS) {
      directory = await getApplicationDocumentsDirectory();
    } else {
      directory = await getDownloadsDirectory();
    }

    if (directory == null) {
      throw Exception('Could not access downloads directory');
    }

    final safeRef =
        transactionReference.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
    final fileName = 'split_bill_receipt_$safeRef.pdf';
    final savedFile = File('${directory.path}/$fileName');
    await savedFile.writeAsBytes(await file.readAsBytes());
    return savedFile.path;
  }

  static Future<void> shareReceipt({
    required String transactionReference,
    required double amount,
    required String currency,
    required String creatorName,
    required String description,
    required int paidCount,
    required int totalParticipants,
  }) async {
    final file = await _generateReceipt(
      transactionReference: transactionReference,
      amount: amount,
      currency: currency,
      creatorName: creatorName,
      description: description,
      paidCount: paidCount,
      totalParticipants: totalParticipants,
    );

    final currencySymbol = _currencySymbolFor(currency);
    final formattedAmount = '$currencySymbol${amount.toStringAsFixed(2)}';

    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      text: 'Split Bill Payment Receipt - $formattedAmount to $creatorName',
      subject: 'LazerVault Split Bill Payment Confirmation',
    ));
  }
}
