// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwjhqLSi7PJGPViP6HPrnljU96qvXjhg',
    appId: '1:961906506476:web:e45eeb296e92e41b3843c9',
    messagingSenderId: '961906506476',
    projectId: 'lazervault-dev',
    authDomain: 'lazervault-dev.firebaseapp.com',
    storageBucket: 'lazervault-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEAzFk-5njxbWtS1GsK9kf1xlwgKak8RY',
    appId: '1:961906506476:android:ec73b0375c4900043843c9',
    messagingSenderId: '961906506476',
    projectId: 'lazervault-dev',
    storageBucket: 'lazervault-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2I8OVG01eg1TOnHo0QGB3kVQHi0zqz0',
    appId: '1:961906506476:ios:a38d37e7cf1d32a33843c9',
    messagingSenderId: '961906506476',
    projectId: 'lazervault-dev',
    storageBucket: 'lazervault-dev.firebasestorage.app',
    iosBundleId: 'com.lazervault.app',
  );
}
