// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqX4NuEAxbxVByrLp0wV6HzIiTOrWFktA',
    appId: '1:169699168674:web:9eaaa15aad9e7f324b22fb',
    messagingSenderId: '169699168674',
    projectId: 'lazervault-testnet',
    authDomain: 'lazervault-testnet.firebaseapp.com',
    storageBucket: 'lazervault-testnet.firebasestorage.app',
    measurementId: 'G-FTXZKSCZRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgKxMAEWU7I9JQOrc5Ufrmv5CN6p_Tek',
    appId: '1:169699168674:android:f9025cedabdafadd4b22fb',
    messagingSenderId: '169699168674',
    projectId: 'lazervault-testnet',
    storageBucket: 'lazervault-testnet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7HN1wPs8T0SPMdcxvLPWBkOezcEeBLw4',
    appId: '1:169699168674:ios:2c427788794ae07d4b22fb',
    messagingSenderId: '169699168674',
    projectId: 'lazervault-testnet',
    storageBucket: 'lazervault-testnet.firebasestorage.app',
    iosBundleId: 'com.lazervault.app',
  );
}
