// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7yvChlEBbBYN8xP9g2bM7Q26EZJoBWQ',
    appId: '1:815870072849:web:1d1b228b03115cec22b9b0',
    messagingSenderId: '815870072849',
    projectId: 'lazervault-28875',
    authDomain: 'lazervault-28875.firebaseapp.com',
    storageBucket: 'lazervault-28875.firebasestorage.app',
    measurementId: 'G-6Q52VLLTP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbef0mBQj2jFJ3bIadX_GR_8lO4zr6AE',
    appId: '1:815870072849:android:c96b67957b35acf922b9b0',
    messagingSenderId: '815870072849',
    projectId: 'lazervault-28875',
    storageBucket: 'lazervault-28875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyr53pwikXO6qrWrYe3AhasUmsyyyF64',
    appId: '1:815870072849:ios:67cced57b9bbdc7222b9b0',
    messagingSenderId: '815870072849',
    projectId: 'lazervault-28875',
    storageBucket: 'lazervault-28875.firebasestorage.app',
    iosBundleId: 'com.lazervault.app',
  );
}
