/// UK Banks Data
/// Comprehensive list of major UK banks for recipient bank name selection
class UKBanksData {
  static const List<String> ukBanks = [
    'Barclays',
    'HSBC',
    'Lloyds Bank',
    'NatWest',
    'Royal Bank of Scotland (RBS)',
    'Santander UK',
    'Nationwide Building Society',
    'Halifax',
    'Bank of Scotland',
    'TSB Bank',
    'Metro Bank',
    'First Direct',
    'Monzo',
    'Starling Bank',
    'Revolut',
    'Virgin Money',
    'Clydesdale Bank',
    'Yorkshire Bank',
    'Co-operative Bank',
    'Danske Bank',
    'Ulster Bank',
    'Allied Irish Bank (GB)',
    'Atom Bank',
    'Aldermore Bank',
    'Cahoot',
    'Cater Allen',
    'C. Hoare & Co',
    'Handelsbanken',
    'Investec Bank',
    'Marks & Spencer Bank',
    'N26',
    'Paragon Bank',
    'Secure Trust Bank',
    'Shawbrook Bank',
    'Tesco Bank',
    'Triodos Bank',
    'Unity Trust Bank',
    'Vanquis Bank',
    'Weatherbys Bank',
    'Zenith Bank',
    'Access Bank UK',
    'Adam & Company',
    'Arbuthnot Latham',
    'Bank of Ireland UK',
    'Bank of London',
    'Bank of Ireland',
    'Citibank',
    'Coutts',
    'Crown Agents Bank',
    'Experian',
    'Gatehouse Bank',
    'ICBC Standard Bank',
    'Ikano Bank',
    'Julius Baer International',
    'Klarna',
    'LazyPay',
    'Lendable',
    'Lloyds Banking Group',
    'MBNA',
    'Modulr',
    'OakNorth Bank',
    'One Savings Bank',
    'PayPal',
    'Post Office Money',
    'Principality Building Society',
    'RCI Bank UK',
    'Redwood Bank',
    'Sainsbury\'s Bank',
    'Skipton Building Society',
    'Starling Bank',
    'Sumitomo Mitsui Banking Corporation',
    'The Bank of New York Mellon',
    'The Northern Trust Company',
    'Tide',
    'Wise (formerly TransferWise)',
    'Zopa Bank',
    'Other',
  ];

  /// Search banks by query
  static List<String> searchBanks(String query) {
    if (query.trim().isEmpty) {
      return ukBanks;
    }

    final lowerQuery = query.toLowerCase();
    return ukBanks.where((bank) => bank.toLowerCase().contains(lowerQuery)).toList();
  }
}
