import 'dart:async';

import 'package:barcode_widget/barcode_widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import '../../../../../core/types/app_routes.dart';
import '../../../authentication/cubit/authentication_cubit.dart';
import '../../services/epin_pdf_service.dart';
import '../cubit/epin_cubit.dart';
import '../cubit/epin_state.dart';
import 'epin_theme.dart';

/// Recharge-card receipt, restyled to match the Send-Funds (unified) receipt:
/// an amount hero, a details card, a QR encoding the transaction reference, and
/// working image (PNG) Download / Share that faithfully render the naira symbol,
/// values and every ePIN detail. The recharge PINs stay as copyable tiles and a
/// printable PDF (all PINs) is offered for handing cards out. Pending orders
/// (PINs generated async) auto-poll until the cards arrive.
class EPinReceiptScreen extends StatefulWidget {
  const EPinReceiptScreen({super.key});

  @override
  State<EPinReceiptScreen> createState() => _EPinReceiptScreenState();
}

class _EPinReceiptScreenState extends State<EPinReceiptScreen> {
  static const _bg = EpinTheme.bg;
  static const _card = EpinTheme.card;
  static const _divider = EpinTheme.divider;
  static const _primary = EpinTheme.primary;
  static const _success = EpinTheme.success;
  static const _warning = EpinTheme.warning;
  static const _error = EpinTheme.error;
  static const _textSecondary = EpinTheme.textSecondary;
  static const _labelColor = Color(0xFF8E8E93);

  /// Back / close returns to the Bills Hub landing the service was launched
  /// from — the route is preserved in the stack (not rebuilt), so the
  /// carousel / active account / locale that sit below it are untouched. Falls
  /// back to the root if the Bills Hub isn't in the stack.
  void _exitToBillsHub() {
    Get.until((route) =>
        route.settings.name == AppRoutes.billsHub || route.isFirst);
  }

  EPinOrder? _order;
  bool _downloading = false;
  bool _sharing = false;

  // The dashboard account the order was paid from (label passed through the
  // flow) — shown in the details as "Paid from".
  String? _accountLabel;

  // The vendor line printed on each recharge card — the explicit business name
  // when set, otherwise the merchant's own profile name.
  String _vendorName = '';

  // The explicit business name (if any) — shown on-screen as confirmation.
  String _businessName = '';

  // Bounded auto-poll for async/pending orders (PINs generated by the consumer):
  // re-fetch every 4s up to ~1 minute so the user doesn't have to tap Refresh.
  Timer? _pollTimer;
  int _pollCount = 0;
  static const _maxPolls = 15;

  @override
  void initState() {
    super.initState();
    final args = Get.arguments as Map<String, dynamic>?;
    String businessName = '';
    if (args != null) {
      _order = args['order'] as EPinOrder?;
      final label = (args['accountLabel'] as String?)?.trim() ?? '';
      if (label.isNotEmpty) _accountLabel = label;
      businessName = (args['businessName'] as String?)?.trim() ?? '';
    }
    // Vendor line on the printout: the name entered this session, else the one
    // persisted on the order (reopened/reprinted orders), else the merchant's
    // own profile name.
    final orderBiz = (_order?.businessName ?? '').trim();
    _businessName = businessName.isNotEmpty ? businessName : orderBiz;
    _vendorName =
        _businessName.isNotEmpty ? _businessName : _resolveVendorName();
    _maybeStartPolling();
  }

  /// The merchant's business name for the printout — the logged-in user's full
  /// name, falling back to their username, else empty (the card omits the line).
  String _resolveVendorName() {
    try {
      final u = context.read<AuthenticationCubit>().currentProfile?.user;
      if (u == null) return '';
      final full = '${u.firstName} ${u.lastName}'.trim();
      if (full.isNotEmpty) return full;
      return (u.username ?? '').trim();
    } catch (_) {
      return '';
    }
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  EPinOrder? get _current => _order;

  String get _reference =>
      (_current?.reference.isNotEmpty ?? false) ? _current!.reference : (_current?.id ?? '');

  void _maybeStartPolling() {
    if (_pollTimer != null) return;
    final order = _current;
    if (order == null || !order.isPending) return;
    _pollTimer = Timer.periodic(const Duration(seconds: 4), (t) {
      if (!mounted) {
        t.cancel();
        return;
      }
      _pollCount++;
      final o = _current;
      if (o == null || !o.isPending || _pollCount >= _maxPolls) {
        t.cancel();
        _pollTimer = null;
        return;
      }
      _refresh();
    });
  }

  void _refresh() {
    final id = _current?.id;
    if (id != null && id.isNotEmpty) {
      context.read<EPinCubit>().loadOrder(id);
    }
  }

  Future<void> _copyPin(String pin) async {
    await Clipboard.setData(ClipboardData(text: pin));
    _snack('PIN copied to clipboard', _success);
  }

  // Download / Share both produce the classic Nigerian recharge-card PRINTOUT
  // (a landscape grid of cut-out cards) via EPinPdfService — the print-ready
  // artefact a vendor hands out, not a screenshot of this screen.
  Future<void> _download() async {
    final order = _current;
    if (order == null || _downloading) return;
    setState(() => _downloading = true);
    try {
      final path = await EPinPdfService.downloadReceipt(
          order: order, vendorName: _vendorName);
      _snack('Recharge cards saved to $path', _success);
    } catch (e, st) {
      debugPrint('[EPin] download cards failed: $e\n$st');
      _snack('Could not save the cards', _warning);
    } finally {
      if (mounted) setState(() => _downloading = false);
    }
  }

  Future<void> _share() async {
    final order = _current;
    if (order == null || _sharing) return;
    setState(() => _sharing = true);
    try {
      await EPinPdfService.printReceipt(order: order, vendorName: _vendorName);
    } catch (e, st) {
      debugPrint('[EPin] print cards failed: $e\n$st');
      _snack('Could not print the cards', _warning);
    } finally {
      if (mounted) setState(() => _sharing = false);
    }
  }

  void _snack(String message, Color color) {
    Get.snackbar(
      '',
      message,
      titleText: const SizedBox.shrink(),
      backgroundColor: color,
      colorText: Colors.white,
      snackPosition: SnackPosition.TOP,
      margin: EdgeInsets.all(16.w),
    );
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) {
        if (!didPop) _exitToBillsHub();
      },
      child: Scaffold(
        backgroundColor: _bg,
        body: SafeArea(
          child: BlocListener<EPinCubit, EPinState>(
            listenWhen: (_, s) => s is EPinOrderLoaded || s is EPinOrderError,
            listener: (context, state) {
              if (state is EPinOrderLoaded) {
                setState(() => _order = state.order);
                if (!state.order.isPending) {
                  _pollTimer?.cancel();
                  _pollTimer = null;
                }
              } else if (state is EPinOrderError) {
                _snack(state.message, _warning);
              }
            },
            child: Column(
              children: [
                _buildHeader(),
                Expanded(child: _buildBody()),
                _buildActions(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildHeader() {
    final order = _current;
    final pending = order?.isPending ?? true;
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 16.h),
      child: Row(
        children: [
          Expanded(
            child: Text(
              pending ? 'Order received' : 'Cards ready',
              style: TextStyle(
                fontSize: 20.sp,
                fontWeight: FontWeight.w700,
                color: Colors.white,
              ),
            ),
          ),
          GestureDetector(
            onTap: _exitToBillsHub,
            child: Container(
              width: 40.w,
              height: 40.w,
              decoration: BoxDecoration(
                color: _card,
                borderRadius: BorderRadius.circular(12.r),
              ),
              child: Icon(Icons.close, color: _textSecondary, size: 20.sp),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBody() {
    final order = _current;
    if (order == null) {
      return const Center(
        child: Text('No order data', style: TextStyle(color: Colors.white)),
      );
    }
    return RefreshIndicator(
      color: _primary,
      onRefresh: () async => _refresh(),
      child: SingleChildScrollView(
        physics: const AlwaysScrollableScrollPhysics(),
        padding: EdgeInsets.symmetric(horizontal: 20.w),
        child: _buildReceiptContent(order),
      ),
    );
  }

  /// The captured/shared receipt surface — amount hero, details + QR, and the
  /// PIN list. Kept free of Bloc/context state so it renders identically both
  /// on-screen and in the offscreen capture.
  Widget _buildReceiptContent(EPinOrder order) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(height: 4.h),
        _buildAmountHero(order),
        SizedBox(height: 20.h),
        // PINs are the whole point of the receipt — keep them up top, not
        // buried below the order details.
        _buildPinsSection(order),
        SizedBox(height: 20.h),
        _buildDetailsCard(order),
        SizedBox(height: 24.h),
      ],
    );
  }

  Widget _buildAmountHero(EPinOrder order) {
    final (label, color) = _statusChip(order);
    String created = '';
    final parsed = DateTime.tryParse(order.createdAt);
    if (parsed != null) {
      created = DateFormat('d MMM yyyy, h:mm a').format(parsed.toLocal());
    }
    return Container(
      width: double.infinity,
      padding: EdgeInsets.symmetric(vertical: 24.h, horizontal: 16.w),
      decoration: BoxDecoration(
        color: _card,
        borderRadius: BorderRadius.circular(16.r),
        border: Border.all(color: _divider),
      ),
      child: Column(
        children: [
          Container(
            width: 52.w,
            height: 52.w,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: color.withValues(alpha: 0.15),
            ),
            child: Icon(
              order.isFailed
                  ? Icons.close
                  : order.isPending
                      ? Icons.hourglass_bottom
                      : Icons.check,
              color: color,
              size: 28.sp,
            ),
          ),
          SizedBox(height: 12.h),
          Text(
            '₦${NumberFormat('#,##0.00').format(order.totalAmount)}',
            style: TextStyle(
              color: Colors.white,
              fontSize: 30.sp,
              fontWeight: FontWeight.w800,
            ),
          ),
          SizedBox(height: 4.h),
          Text(
            'Recharge cards · ${order.network}',
            style: TextStyle(color: _textSecondary, fontSize: 13.sp),
          ),
          SizedBox(height: 12.h),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding: EdgeInsets.symmetric(horizontal: 10.w, vertical: 4.h),
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(20.r),
                ),
                child: Text(
                  label,
                  style: TextStyle(
                    color: color,
                    fontSize: 12.sp,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              if (created.isNotEmpty) ...[
                SizedBox(width: 8.w),
                Text('·', style: TextStyle(color: _textSecondary)),
                SizedBox(width: 8.w),
                Text(created,
                    style:
                        TextStyle(color: _textSecondary, fontSize: 12.sp)),
              ],
            ],
          ),
        ],
      ),
    );
  }

  (String, Color) _statusChip(EPinOrder order) {
    if (order.isFailed) return ('Failed', _error);
    if (order.isPending) return ('Awaiting verification', _warning);
    return ('Completed', _success);
  }

  Widget _buildDetailsCard(EPinOrder order) {
    return Container(
      width: double.infinity,
      padding: EdgeInsets.all(16.w),
      decoration: BoxDecoration(
        color: _card,
        borderRadius: BorderRadius.circular(14.r),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Details',
            style: TextStyle(
              color: Colors.white,
              fontSize: 15.sp,
              fontWeight: FontWeight.w600,
            ),
          ),
          SizedBox(height: 14.h),
          _detailRow('Network', order.network),
          _detailRow(
              'Denomination', '₦${order.denomination.toStringAsFixed(0)}'),
          _detailRow('Quantity', '${order.quantity}'),
          if (order.serviceFee > 0)
            _detailRow('Service fee',
                '₦${order.serviceFee.toStringAsFixed(2)}'),
          if (_businessName.isNotEmpty)
            _detailRow('Printed as', _businessName),
          if (_accountLabel != null) _detailRow('Paid from', _accountLabel!),
          _detailRow('Reference', _reference),
          _detailRow(
              'Total paid', '₦${order.totalAmount.toStringAsFixed(2)}',
              emphasise: true),
          SizedBox(height: 6.h),
          Divider(color: _divider, height: 1),
          SizedBox(height: 14.h),
          Center(
            child: SizedBox(
              height: 80.w,
              width: 80.w,
              child: BarcodeWidget(
                barcode: Barcode.qrCode(),
                data: _reference,
                drawText: false,
                color: Colors.white,
                backgroundColor: Colors.transparent,
              ),
            ),
          ),
          SizedBox(height: 6.h),
          Center(
            child: Text(
              _reference,
              style: TextStyle(
                fontSize: 10.sp,
                color: _labelColor,
                fontFamily: 'RobotoMono',
                letterSpacing: 0.5,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _detailRow(String label, String value, {bool emphasise = false}) {
    return Padding(
      padding: EdgeInsets.only(bottom: 10.h),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 110.w,
            child: Text(
              label,
              style: TextStyle(color: _labelColor, fontSize: 13.sp),
            ),
          ),
          Expanded(
            child: Text(
              value,
              textAlign: TextAlign.right,
              style: TextStyle(
                color: Colors.white,
                fontSize: 13.sp,
                fontWeight: emphasise ? FontWeight.w800 : FontWeight.w500,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPinsSection(EPinOrder order) {
    final cardsWithPins = order.cards.where((c) => c.hasPin).toList();
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text(
              'Recharge PINs',
              style: TextStyle(
                color: Colors.white,
                fontSize: 16.sp,
                fontWeight: FontWeight.w700,
              ),
            ),
            if (cardsWithPins.isNotEmpty) ...[
              SizedBox(width: 8.w),
              Container(
                padding: EdgeInsets.symmetric(horizontal: 8.w, vertical: 2.h),
                decoration: BoxDecoration(
                  color: _primary.withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(20.r),
                ),
                child: Text('${cardsWithPins.length}',
                    style: TextStyle(
                        color: _primary,
                        fontSize: 11.sp,
                        fontWeight: FontWeight.w700)),
              ),
            ],
            const Spacer(),
            // Show Refresh while pending, but ALSO when no PIN has surfaced yet
            // — a post-charge-ambiguous order can flip to "completed" with zero
            // cards, and the user still needs a way to re-fetch for the PIN.
            if (order.isPending || cardsWithPins.isEmpty)
              GestureDetector(
                onTap: _refresh,
                child: Row(
                  children: [
                    Icon(Icons.refresh, color: _primary, size: 16.sp),
                    SizedBox(width: 4.w),
                    Text('Refresh',
                        style: TextStyle(color: _primary, fontSize: 13.sp)),
                  ],
                ),
              ),
          ],
        ),
        SizedBox(height: 4.h),
        Text(
          'Keep these safe — treat them like cash.',
          style: TextStyle(color: _textSecondary, fontSize: 11.5.sp),
        ),
        SizedBox(height: 12.h),
        if (cardsWithPins.isEmpty)
          Container(
            width: double.infinity,
            padding: EdgeInsets.all(16.w),
            decoration: BoxDecoration(
              color: _card,
              borderRadius: BorderRadius.circular(12.r),
              border: Border.all(color: _divider),
            ),
            child: Text(
              order.isPending
                  ? 'Your PINs are being generated. Tap Refresh in a moment to reveal them.'
                  : "No PINs have surfaced yet. Tap Refresh to check again — if they still don't appear, our team will resolve it.",
              style: TextStyle(color: _textSecondary, fontSize: 13.sp),
            ),
          )
        else
          ...cardsWithPins.map(_buildPinTile),
      ],
    );
  }

  Widget _buildPinTile(EPinCard card) {
    return Container(
      margin: EdgeInsets.only(bottom: 10.h),
      padding: EdgeInsets.all(14.w),
      decoration: BoxDecoration(
        color: _card,
        borderRadius: BorderRadius.circular(12.r),
        border: Border.all(color: _primary.withValues(alpha: 0.25)),
      ),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  card.productName.isNotEmpty ? card.productName : 'Recharge PIN',
                  style: TextStyle(
                    color: _textSecondary,
                    fontSize: 10.5.sp,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0.5,
                  ),
                ),
                SizedBox(height: 6.h),
                Text(
                  card.pin,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20.sp,
                    fontWeight: FontWeight.w800,
                    letterSpacing: 2,
                    fontFamily: 'RobotoMono',
                  ),
                ),
                if (card.serial.isNotEmpty) ...[
                  SizedBox(height: 6.h),
                  Text(
                    'Serial ${card.serial}',
                    style: TextStyle(color: _textSecondary, fontSize: 11.sp),
                  ),
                ],
              ],
            ),
          ),
          SizedBox(width: 10.w),
          GestureDetector(
            onTap: () => _copyPin(card.pin),
            child: Container(
              width: 44.w,
              height: 44.w,
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: _primary.withValues(alpha: 0.15),
                borderRadius: BorderRadius.circular(12.r),
              ),
              child: Icon(Icons.copy, color: _primary, size: 18.sp),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildActions() {
    final order = _current;
    final enabled = order != null && !order.isFailed;
    return Container(
      padding: EdgeInsets.fromLTRB(20.w, 8.h, 20.w, 12.h),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: enabled && !_downloading ? _download : null,
                  icon: _downloading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                              color: _primary, strokeWidth: 2),
                        )
                      : Icon(Icons.download, size: 18.sp, color: _primary),
                  label: Text('Download cards',
                      style: TextStyle(color: _primary, fontSize: 14.sp)),
                  style: OutlinedButton.styleFrom(
                    side: const BorderSide(color: _primary),
                    padding: EdgeInsets.symmetric(vertical: 14.h),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14.r),
                    ),
                  ),
                ),
              ),
              SizedBox(width: 12.w),
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: enabled && !_sharing ? _share : null,
                  icon: _sharing
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                              color: Colors.white, strokeWidth: 2),
                        )
                      : Icon(Icons.print_rounded, size: 18.sp, color: Colors.white),
                  label: Text('Print cards',
                      style: TextStyle(fontSize: 14.sp, color: Colors.white)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _primary,
                    disabledBackgroundColor: _primary.withValues(alpha: 0.3),
                    foregroundColor: Colors.white,
                    elevation: 0,
                    padding: EdgeInsets.symmetric(vertical: 14.h),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14.r),
                    ),
                  ),
                ),
              ),
            ],
          ),
          SizedBox(height: 8.h),
          Text('Downloads a print-ready PDF of the recharge cards',
              style: TextStyle(color: _textSecondary, fontSize: 11.sp)),
        ],
      ),
    );
  }
}
